test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: development
  pool: 5
  username: root
  password: password
  socket: /var/lib/mysql/mysql.sock
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  wait_timeout: 31536000
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  # socket:   <%=ENV['OPENSHIFT_MYSQL_DB_SOCKET']%>
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
